name: Build and Release WSL Fedora for DevOps

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t dvp-fedora .

    - name: Export Docker container to .tar
      run: |
        docker create --name dvp_fedora_container dvp-fedora
        docker export dvp_fedora_container > dvp-fedora.tar
        docker rm dvp_fedora_container

    - name: Split the .tar file into chunks
      run: split -b 1900M dvp-fedora.tar dvp-fedora-part-

    - name: Upload chunks as release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dvp-fedora-part-*
        asset_name: "dvp-fedora-part-"
        asset_content_type: application/octet-stream
