name: Build and Release WSL Fedora for DevOps

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build Docker image
    - name: Build Docker image
      run: docker build -t dvp-fedora .

    # Step 3: Export Docker container to .tar
    - name: Export Docker container to .tar
      run: |
        docker create --name dvp_fedora_container dvp-fedora
        docker export dvp_fedora_container > dvp-fedora.tar
        docker rm dvp_fedora_container

    # Step 4: Split the .tar file into chunks
    - name: Split the .tar file into smaller chunks
      run: split -b 1900M dvp-fedora.tar dvp-fedora-part-

    # Step 5: Install GitHub CLI (if not already available)
    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    # Step 6: Upload chunks to the GitHub release
    - name: Upload chunks as release assets
      shell: bash
      run: |
        for file in dvp-fedora-part-*; do
          echo "Uploading $file"
          gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
        done

    # Step 7: Clean up temporary files
    - name: Cleanup temporary files
      run: rm -f dvp-fedora-part-* dvp-fedora.tar
